
spring:
  profiles:
    active: local

---

#spring:
#  profiles: local
#  datasource:
#    platform: h2
#    url: jdbc:h2:tcp://localhost:9092/mem:testdb;MVCC=TRUE;DB_CLOSE_ON_EXIT=FALSE
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#
#  jpa:
#    database-platform: H2
#    show-sql: false
#    hibernate:
#      ddl-auto: create-drop
#logging:
#  level:
#    ROOT: debug


#mysql
#---
spring:
  profiles: local
  jpa:
    database: mysql
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
  datasource:
#    data: classpath:data-h2.sql # 시작할때 실행시킬 script
    url: jdbc:mysql://localhost:3306/booktest?useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    platform: test

logging:
  level:
    ROOT: info
